import * as codebuild from '@aws-cdk/aws-codebuild';
import * as codecommit from '@aws-cdk/aws-codecommit';
import * as codepipeline from '@aws-cdk/aws-codepipeline';
import * as codepipeline_actions from '@aws-cdk/aws-codepipeline-actions';
import * as iam from '@aws-cdk/aws-iam';
import * as s3 from '@aws-cdk/aws-s3';
import * as cdk from '@aws-cdk/core';
import * as compliant_constructs from '@aws-compliant-constructs/compliant-constructs';
import * as config_repository from './config-repository';
import * as accelerator from '@aws-accelerator/accelerator';

export interface AcceleratorPipelineProps {
  readonly sourceRepositoryName: string;
  readonly sourceBranchName: string;
}

/**
 * AWS Accelerator Pipeline Class, which creates the pipeline for AWS Landing zone
 */
export class AcceleratorPipeline extends cdk.Construct {
  constructor(scope: cdk.Construct, id: string, props: AcceleratorPipelineProps) {
    super(scope, id);

    const bucket = new compliant_constructs.SecureS3Bucket(this, 'SecureBucket', {
      s3BucketName: `aws-accelerator-pipeline-${cdk.Stack.of(this).account}-${cdk.Stack.of(this).region}`,
      kmsAliasName: 'alias/accelerator/pipeline/s3',
      kmsDescription: 'AWS Accelerator Pipeline Bucket CMK',
    });

    // cfn_nag: Suppress warning related to the pipeline artifacts S3 bucket
    const cfnBucket = bucket.node.defaultChild?.node.defaultChild as s3.CfnBucket;
    cfnBucket.cfnOptions.metadata = {
      cfn_nag: {
        rules_to_suppress: [
          {
            id: 'W35',
            reason: 'S3 Bucket access logging is not enabled for the pipeline artifacts bucket.',
          },
        ],
      },
    };

    const configRepository = new config_repository.ConfigRepository(this, 'ConfigRepository', {
      repositoryName: 'accelerator-config',
      repositoryBranchName: 'main',
      description:
        'AWS Accelerator configuration repository, created and initialized with default config file by pipeline',
    });

    /**
     * Pipeline
     */
    const pipelineRole = new iam.Role(this, 'PipelineRole', {
      assumedBy: new iam.ServicePrincipal('codepipeline.amazonaws.com'),
    });

    const pipeline = new codepipeline.Pipeline(this, 'Resource', {
      pipelineName: 'AWS-Accelerator',
      artifactBucket: bucket.getS3Bucket(),
      role: pipelineRole,
    });

    // cfn_nag: Suppress warning related to high SPCM score
    const cfnPipelinePolicy = pipeline.role.node.findChild('DefaultPolicy').node.defaultChild as iam.CfnPolicy;
    cfnPipelinePolicy.cfnOptions.metadata = {
      cfn_nag: {
        rules_to_suppress: [
          {
            id: 'W76',
            reason: 'This policy is generated by CDK which can cause a high SPCM score.',
          },
        ],
      },
    };

    const acceleratorRepoArtifact = new codepipeline.Artifact('Source');
    const configRepoArtifact = new codepipeline.Artifact('Config');

    pipeline.addStage({
      stageName: 'Source',
      actions: [
        new codepipeline_actions.CodeCommitSourceAction({
          actionName: 'Source',
          repository: codecommit.Repository.fromRepositoryName(this, 'SourceRepo', props.sourceRepositoryName),
          branch: props.sourceBranchName,
          output: acceleratorRepoArtifact,
          trigger: codepipeline_actions.CodeCommitTrigger.NONE,
        }),
        new codepipeline_actions.CodeCommitSourceAction({
          actionName: 'Configuration',
          repository: configRepository.getRepository(),
          branch: 'main',
          output: configRepoArtifact,
          trigger: codepipeline_actions.CodeCommitTrigger.NONE,
        }),
      ],
    });

    /**
     * Build Stage
     */
    const buildRole = new iam.Role(this, 'BuildRole', {
      assumedBy: new iam.ServicePrincipal('codebuild.amazonaws.com'),
    });

    const buildProject = new codebuild.PipelineProject(this, 'BuildProject', {
      projectName: 'AWS-Accelerator-BuildProject',
      role: buildRole,
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '0.2',
        phases: {
          install: {
            'runtime-versions': {
              nodejs: 14,
            },
          },
          build: {
            commands: ['cd source', 'yarn install', 'yarn lerna bootstrap', 'yarn build'],
          },
        },
        artifacts: {
          files: ['**/*'],
          'enable-symlinks': 'yes',
        },
      }),
      environment: {
        buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
        privileged: true, // Allow access to the Docker daemon
        computeType: codebuild.ComputeType.MEDIUM,
        environmentVariables: {
          ACCELERATOR_NAME: {
            type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
            value: 'aws-accelerator',
          },
        },
      },
      cache: codebuild.Cache.local(codebuild.LocalCacheMode.SOURCE),
    });

    const buildOutput = new codepipeline.Artifact('Build');

    pipeline.addStage({
      stageName: 'Build',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Build',
          project: buildProject,
          input: acceleratorRepoArtifact,
          outputs: [buildOutput],
          role: pipelineRole,
        }),
      ],
    });

    /**
     * Deploy Stage
     */
    const toolkitRole = new iam.Role(this, 'ToolkitRole', {
      assumedBy: new iam.ServicePrincipal('codebuild.amazonaws.com'),
      managedPolicies: [iam.ManagedPolicy.fromAwsManagedPolicyName('AdministratorAccess')],
    });

    const toolkitProject = new codebuild.PipelineProject(this, 'ToolkitProject', {
      projectName: 'AWS-Accelerator-ToolkitProject',
      role: toolkitRole,
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '0.2',
        phases: {
          install: {
            'runtime-versions': {
              nodejs: 14,
            },
          },
          build: {
            commands: [
              'env',
              'cd source',
              'cd packages/@aws-accelerator/accelerator',
              'npx ts-node --transpile-only cdk.ts $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config',
            ],
          },
        },
      }),
      environment: {
        buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
        privileged: true, // Allow access to the Docker daemon
        computeType: codebuild.ComputeType.MEDIUM,
        environmentVariables: {
          ACCELERATOR_NAME: {
            type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
            value: 'aws-accelerator',
          },
        },
      },
      cache: codebuild.Cache.local(codebuild.LocalCacheMode.SOURCE),
    });

    pipeline.addStage({
      stageName: 'Bootstrap',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Bootstrap',
          runOrder: 1,
          project: toolkitProject,
          input: buildOutput,
          extraInputs: [configRepoArtifact],
          role: pipelineRole,
          environmentVariables: {
            CDK_OPTIONS: {
              type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
              // TODO: Investigate how to bootstrap using CLI stackless
              value: `bootstrap --stage ${accelerator.Stage.VALIDATE}`,
            },
          },
        }),
      ],
    });

    pipeline.addStage({
      stageName: 'Validate',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Validate',
          runOrder: 1,
          project: toolkitProject,
          input: buildOutput,
          extraInputs: [configRepoArtifact],
          role: pipelineRole,
          environmentVariables: {
            CDK_OPTIONS: {
              type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
              value: `deploy --stage ${accelerator.Stage.VALIDATE}`,
            },
          },
        }),
      ],
    });

    pipeline.addStage({
      stageName: 'Organization',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Accounts',
          runOrder: 2,
          project: toolkitProject,
          input: buildOutput,
          extraInputs: [configRepoArtifact],
          role: pipelineRole,
          environmentVariables: {
            CDK_OPTIONS: {
              type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
              value: `deploy --stage accounts`,
            },
          },
        }),
      ],
    });

    pipeline.addStage({
      stageName: 'Dependencies',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Dependencies',
          runOrder: 3,
          project: toolkitProject,
          input: buildOutput,
          extraInputs: [configRepoArtifact],
          role: pipelineRole,
          environmentVariables: {
            CDK_OPTIONS: {
              type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
              value: `deploy --stage dependencies`,
            },
          },
        }),
      ],
    });

    pipeline.addStage({
      stageName: 'Deploy',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Security',
          runOrder: 4,
          project: toolkitProject,
          input: buildOutput,
          extraInputs: [configRepoArtifact],
          role: pipelineRole,
          environmentVariables: {
            CDK_OPTIONS: {
              type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
              value: `deploy --stage security`,
            },
          },
        }),
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Operations',
          runOrder: 5,
          project: toolkitProject,
          input: buildOutput,
          extraInputs: [configRepoArtifact],
          role: pipelineRole,
          environmentVariables: {
            CDK_OPTIONS: {
              type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
              value: `deploy --stage operations`,
            },
          },
        }),
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Networking',
          runOrder: 6,
          project: toolkitProject,
          input: buildOutput,
          extraInputs: [configRepoArtifact],
          role: pipelineRole,
          environmentVariables: {
            CDK_OPTIONS: {
              type: codebuild.BuildEnvironmentVariableType.PLAINTEXT,
              value: `deploy --stage networking`,
            },
          },
        }),
      ],
    });
  }
}
