/**
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
 *  with the License. A copy of the License is located at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
 *  OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
 *  and limitations under the License.
 */

/**
 * Snapshot Tests for InstallerContainerStack
 *
 * These tests validate the CloudFormation template generated by InstallerContainerStack
 * under various configuration scenarios. Each test captures a snapshot of the synthesized
 * CloudFormation template and compares it against saved snapshots.
 *
 * Test Coverage:
 * - Default configuration (standard deployment)
 * - External pipeline account mode (cross-account deployment)
 * - Permission boundary enabled (restricted IAM permissions)
 * - S3 source configuration (custom source location)
 * - Single account mode (simplified deployment)
 *
 * Running Tests:
 * - Run all tests: `yarn test:unit`
 * - Run with coverage: `yarn test:unit --coverage`
 * - Update snapshots: `yarn test:unit -u`
 * - Run specific test: `yarn test:unit -t "Default Configuration"`
 *
 * When to Update Snapshots:
 * - After intentional infrastructure changes
 * - When adding new resources to the stack
 * - When modifying stack properties or parameters
 * - Review the diff carefully before updating!
 *
 * Troubleshooting:
 * - If tests fail with "Cannot find module" errors, run `yarn build` in dependency packages
 * - If snapshots show unexpected changes, review the CloudFormation diff carefully
 * - Large snapshot diffs may indicate unintended changes - investigate before updating
 */

import * as cdk from 'aws-cdk-lib';
import { describe } from 'vitest';
import { snapShotTest } from './snapshot-test';
import { InstallerContainerStack } from '../lib/installer-container-stack';

describe('InstallerContainerStack', () => {
  /**
   * Test 1: Default Configuration
   *
   * Tests the stack with all optional features disabled. This represents
   * the most common deployment scenario for new installations.
   *
   * Key Resources Validated:
   * - CloudFormation parameters (ECR URI, account emails, etc.)
   * - KMS key for encryption
   * - S3 buckets (config and access logs)
   * - VPC and networking resources
   * - ECS task definition and cluster
   */
  snapShotTest('Construct(InstallerContainerStack): Default Configuration', () => {
    const app = new cdk.App();
    return new InstallerContainerStack(app, 'TestInstallerContainerStack', {
      useExternalPipelineAccount: false,
      useS3Source: false,
      enableSingleAccountMode: false,
      usePermissionBoundary: false,
      setNodeVersion: false,
    });
  });

  /**
   * Test 2: External Pipeline Account Mode
   *
   * Tests the stack configured for deployment from an external pipeline account.
   * This mode adds additional CloudFormation parameters for cross-account access.
   *
   * Additional Resources Validated:
   * - AcceleratorQualifier parameter
   * - ManagementAccountId parameter
   * - ManagementAccountRoleName parameter
   * - Cross-account IAM role configurations
   */
  snapShotTest('Construct(InstallerContainerStack): With External Pipeline Account', () => {
    const app = new cdk.App();
    return new InstallerContainerStack(app, 'TestInstallerContainerStackExternal', {
      useExternalPipelineAccount: true,
      useS3Source: false,
      enableSingleAccountMode: false,
      usePermissionBoundary: false,
      setNodeVersion: false,
    });
  });

  /**
   * Test 3: Permission Boundary Enabled
   *
   * Tests the stack with IAM permission boundaries enabled. This is required
   * for organizations with strict security policies that limit IAM permissions.
   *
   * Additional Resources Validated:
   * - PermissionBoundaryPolicyName parameter
   * - IAM roles with permission boundary attached
   * - Policy configurations respecting the boundary
   */
  snapShotTest('Construct(InstallerContainerStack): With Permission Boundary', () => {
    const app = new cdk.App();
    return new InstallerContainerStack(app, 'TestInstallerContainerStackPermBoundary', {
      useExternalPipelineAccount: false,
      useS3Source: false,
      enableSingleAccountMode: false,
      usePermissionBoundary: true,
      setNodeVersion: false,
    });
  });

  /**
   * Test 4: S3 Source Configuration
   *
   * Tests the stack configured to use an existing S3 bucket as the source
   * for LZA code instead of ECR. Includes KMS key ARN for encrypted buckets.
   *
   * Additional Resources Validated:
   * - S3 source bucket references
   * - KMS key permissions for S3 access
   * - Modified ECS task definition for S3 source
   */
  snapShotTest('Construct(InstallerContainerStack): With S3 Source', () => {
    const app = new cdk.App();
    return new InstallerContainerStack(app, 'TestInstallerContainerStackS3', {
      useExternalPipelineAccount: false,
      useS3Source: true,
      s3SourceKmsKeyArn: 'arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012',
      enableSingleAccountMode: false,
      usePermissionBoundary: false,
      setNodeVersion: false,
    });
  });

  /**
   * Test 5: Single Account Mode
   *
   * Tests the stack configured for single-account deployment. This simplified
   * mode is useful for testing or small deployments that don't require
   * multi-account organization structure.
   *
   * Modified Resources Validated:
   * - Simplified IAM permissions
   * - Reduced cross-account configurations
   * - Single-account-specific parameters
   */
  snapShotTest('Construct(InstallerContainerStack): Single Account Mode', () => {
    const app = new cdk.App();
    return new InstallerContainerStack(app, 'TestInstallerContainerStackSingleAccount', {
      useExternalPipelineAccount: false,
      useS3Source: false,
      enableSingleAccountMode: true,
      usePermissionBoundary: false,
      setNodeVersion: false,
    });
  });
});
