#!/bin/sh

# Fail if any command fails.
set -e

. "$(dirname "$0")/_/husky.sh"

cd source
# lint staged files only, command defined in package.json
npx lint-staged
# ensure package.json and yarn.lock are in sync
yarn check --integrity

# Display Console logs from changed files
yarn run scan-logging
