#!/bin/sh

# Fail if any command fails.
set -e

. "$(dirname "$0")/_/husky.sh"

# pre-commit viper scan
wget -v 'https://s3.amazonaws.com/viperlight-scanner/latest/viperlight.zip'
unzip -qo viperlight.zip -d ../viperlight
rm -r ./viperlight.zip
../viperlight/bin/viperlight scan
cd source
yarn lerna run precommit --stream
# Validate all enabled config files
yarn validate-config packages/@aws-accelerator/accelerator/test/configs/all-enabled/
yarn run test 
